plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id("com.bouncingelf10.minecraft-version-compatibility-checker") version "1.7.0"
	id "me.modmuss50.mod-publish-plugin" version "2.0.0"
}

version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "maven.modrinth:timelesslib:${project.timelesslib_version}"

	implementation(include("net.java.dev.jna:jna:5.14.0"))
	implementation(include("net.java.dev.jna:jna-platform:5.14.0"))
}

publishMods {
	file = jar.archiveFile
	changelog = "Initial 26.1-26.1.2 release"
	type = STABLE
	modLoaders.add("fabric")

	curseforge {
		projectId = "1576204"
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		minecraftVersions.add("26.1.2")
		minecraftVersions.add("26.1.1")
		minecraftVersions.add("26.1")
		client = true
		server = true
		requires("timelesslib")
	}
	modrinth {
		projectId = "bXiW90yr"
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		minecraftVersions.add("26.1.2")
		minecraftVersions.add("26.1.1")
		minecraftVersions.add("26.1")
		requires("timelesslib")
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
